services:
  beca-database:
    image: mariadb:11
    container_name: mariadb-becajava
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: becajava
      MARIADB_USER: becajava
      MARIADB_PASSWORD: becajava
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-init:
    image: alpine:3.19
    container_name: kafka-init
    command: >
      sh -c "chown -R 1000:1000 /data"
    volumes:
      - kafka_data:/data
    restart: "no"

  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    hostname: kafka
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    #    user: "0:0"
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  mariadb_data:
  kafka_data:

