spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    default-property-inclusion: non_null
  application:
    name: ms-transaction-api
services:
  external:
    ms-api-check: http://localhost:8081/api/v1/customers/check

