spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mariadb://localhost:3306/becajava
    username: becajava
    password: becajava
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    resolve-schema-properties: true
  swagger-ui:
    url: /openapi/openapi.yaml
    path: /swagger-ui.html
server:
  port: 8082

services:
  external:
    ms-api-check: http://localhost:8081/api/v1/customers/check

