openapi: 3.0.3

info:
  title: API do Microserviço do Cliente
  version: 1.0.0
  contact:
    name: Swellington Soares
  description: >
    API REST para autenticação e gestão de clientes (customers), incluindo cadastro em lote via upload.

servers:
  - url: http://localhost:8081
    description: Local
security:
  - bearerAuth: [ ]

paths:
  /api/v1/auth/login:
    $ref: '/paths/auth/login.yaml'
  /api/v1/auth/refresh:
    $ref: '/paths/auth/refresh-token.yaml'
  /api/v1/customers:
    $ref: '/paths/customers/customer-root.yaml'
  /api/v1/customers/{id}:
    $ref: '/paths/customers/customer-domain.yaml'
  /api/v1/customers/batch-register:
    $ref: '/paths/customers/batch-register.yaml'
  /api/v1/customers/batch-register/{id}:
    $ref: '/paths/customers/batch-register-status.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT








