spring:
  application:
    name: ms-transaction-processor
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transaction-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: dev.suel.*
        spring.json.value.default.type: dev.suel.gestaofinanceira.types.TransactionKafkaEventData
services:
  external:
    cambio-api: https://economia.awesomeapi.com.br/json/last
    mock-api: https://696f7560a06046ce6186c5c6.mockapi.io/api/v1

