spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:mariadb://localhost:3306/becajava
    username: becajava
    password: becajava
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
